services:
  bytesocks:
    image: ghcr.io/lucko/bytesocks
    ports:
      - 3000:8080
    environment:
      # You can configure bytesocks using
      # environment variables.
      BYTESOCKS_MISC_KEYLENGTH: 15
